include:
  - project: 'tcs-atm/ci-templates'
    file: '/java-library.yml'

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - ./gradlew clean build -x test

test:
  stage: test
  script:
    - ./gradlew test

publish:
  stage: publish
  script:
    - ./gradlew publish
  only:
    - master
    - tags
